version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(levelname)s: %(message)s'
  json:
    (): my_json_formatter.MyJSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/my_app.log.jsonl
    when: midnight
    backupCount: 10
loggers:
  root:
    level: DEBUG
    handlers:
      - stderr
      - file
